import dotenv from "dotenv";
import { build } from "electron-builder";

dotenv.config();

build({
  config: {
    productName: "LeafView",
    appId: "jp.wassabie64.LeafView",
    artifactName: "${productName}-${version}-${platform}-${arch}.${ext}",
    copyright: "© 2020 sprout2000 and other contributors.",
    directories: {
      output: "release",
      buildResources: "assets",
    },
    files: [
      "dist/**/*",
      "!node_modules/@electron/notarize",
      "!node_modules/@jest/types",
      "!node_modules/@testing-library/dom",
      "!node_modules/@testing-library/jest-dom",
      "!node_modules/@testing-library/react",
      "!node_modules/@testing-library/user-event",
      "!node_modules/@types/jest",
      "!node_modules/@types/leaflet",
      "!node_modules/@types/mime-types",
      "!node_modules/@types/node",
      "!node_modules/@types/react",
      "!node_modules/@types/react-dom",
      "!node_modules/@typescript-eslint/eslint-plugin",
      "!node_modules/@typescript-eslint/parser",
      "!node_modules/copy-webpack-plugin",
      "!node_modules/cross-env",
      "!node_modules/css-loader",
      "!node_modules/dotenv",
      "!node_modules/electron-builder",
      "!node_modules/electronmon",
      "!node_modules/eslint",
      "!node_modules/eslint-config-prettier",
      "!node_modules/eslint-plugin-react",
      "!node_modules/eslint-plugin-react-hooks",
      "!node_modules/html-webpack-plugin",
      "!node_modules/jest",
      "!node_modules/jest-environment-jsdom",
      "!node_modules/mini-css-extract-plugin",
      "!node_modules/npm-run-all",
      "!node_modules/prettier",
      "!node_modules/rimraf",
      "!node_modules/sass",
      "!node_modules/sass-loader",
      "!node_modules/ts-jest",
      "!node_modules/ts-loader",
      "!node_modules/ts-node",
      "!node_modules/typescript",
      "!node_modules/webpack",
      "!node_modules/wait-on",
      "!node_modules/webpack-cli",
    ],
    asarUnpack: ["dist/images/logo.png"],
    win: {
      icon: "assets/icon.ico",
      target: ["appx"],
      publisherName: "sprout2000",
      fileAssociations: [
        {
          ext: ["bmp", "gif", "jpeg", "jpg", "png", "ico", "svg", "webp"],
          description: "Image files",
        },
      ],
    },
    appx: {
      backgroundColor: "#ffffff",
      displayName: "LeafView",
      showNameOnTiles: true,
      languages: ["en-US", "ja-JP"],
      publisherDisplayName: "sprout2000",
      applicationId: "sprout2000.LeafView",
      publisher: process.env.PUBLISHER,
      identityName: process.env.IDENTITY_NAME,
    },
  },
});
