name: GitHub Pages

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: '14.x'
      - name: Install
        run: yarn install --frozen-lockfile --ignore-optional
      - name: Build
        run: yarn build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
